# Generated by Django 3.0.2 on 2020-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_dewey_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='dewey',
            old_name='name_dewey',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=61, null=True),
        ),
    ]
