# Generated by Django 3.0.2 on 2020-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=61, null=True),
        ),
    ]
