# Generated by Django 3.0.2 on 2020-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200107_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('-', 'Indéfini'), ('B', 'Livre'), ('M', 'Musique'), ('F', 'Film')], default='-', max_length=1),
        ),
    ]
