# Generated by Django 3.0.2 on 2020-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200108_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
