# Generated by Django 3.0.2 on 2020-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_publication_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
