# Generated by Django 3.0.2 on 2020-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200109_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'verbose_name': 'Auteur'},
        ),
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number'], 'verbose_name': 'Classement Dewey'},
        ),
        migrations.AlterField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
    ]
